### PR TITLE
Add dist/ folder with latest release

### PR DESCRIPTION
**Pull request by mdamien**
On pending question: There is the source map line in each minified file but not the source map itself, is it a problem ?

### CODE REVIEW

**Comment by sheymann** [comment]
Can we add the map files?

**Comment by sheymann** [comment]
rel: #210

**Comment by mdamien** [comment]
This, and also the unminified files I think

**Comment by sheymann** [comment]
indeed

**Comment by mdamien** [comment]
I couldn't reproduce the released minified files (may be due to a different uglify-js versions).

So I'm including my own minified files and I'm pinning the uglify-js version

**Pull request merged**
