### PR TITLE
Plugin/djikstra

### PR DESCRIPTION
**Pull request by YannGrenier**

### CODE REVIEW

**Comment by YannGrenier** [comment]
2nd round of reviews has been completed

**Comment by sheymann** [comment]
Thanks @YannGrenier but there are still critical issues with your code that prevent to merge it:

### 1

Please re-indent the code and comments to improve its readability. It is still a real mess! See how other plugins are written to figure out the gap.

### 3

I've not been clear enough: you should **not** use any `try/catch` for logging an exception:

```js
try{ ...
}catch(err){
	console.log(err);
	throw(err);
}
```

is useless in **any** language.

### 6

Why did you edit the file *sigma.helpers.graph/LICENSE*? This is the GPL license and you don't have the right to do so because you are not the author of *sigma.helpers.graph*. Moreover, simply replacing "GPL" with "MIT" in the license text makes no sense. Please revert your changes on this file.

### 7

still not fixed:
- missing test on disconnected graph.
- missing comments on tests and test graphs, it's till not possible to understand what is tested.
- tests messages gives poor information on the limit cases tested behind, e.g. "dijkstra returns the correct distances on a 10-node graph".

**Comment by YannGrenier** [comment]
Hi Sebastien !
It should be easier to read now. The problem came from the indentation in my code editor.

As far as the tests are concerned though:

"dijkstra" returns the correct distances on a 10-node graph (first entry node)
"dijkstra" returns the correct distances on a 10-node graph (second entry node)
"dijkstra" returns the correct distances on a 10-node graph (third entry node)

the three above are not really limit cases, i'm just testing the method on random nodes on a larger graph
I'm not really sure how it should be written though, hoped you could give me some advice on that

**Comment by sheymann** [comment]
Hi @YannGrenier, it's better!

## 3

I'm not sure to understand why using try/catch on lines 127-128, and 146-147:

```js
try{...} catch(err){throw(err);}
```

because it's equivalent of not using try/catch.

## 7

It's good to test normal cases if you explain well enough for other developers. If I draw the graph "graph2" I see that it has a precise shape: you should comment all graphs to describe them so that other developers can understand it. Basically I can't  understand the tests by reading them and this is a big issue.

Tests should also cover limit cases. This is why you have a test on negative edge weight. Limit cases may be more subtle, and should be added when we suspect that the algorithm may not behave as expected, or the description of the implementation doesn't answer a question (such as What if the graph is disconnected?).

On tests expecting exceptions, please use [QUnit.throws](https://api.qunitjs.com/throws/) instead of using try/catch in tests.

## 8

What is the complexity of the implementation?

**Pull request closed without merging**
