### PR TITLE
add label alignment settings for canvas

### PR DESCRIPTION
**Pull request by qinfchen**
Create a separate PR for linkurious, the original PR to sigmajs is here https://github.com/jacomyal/sigma.js/pull/468

### CODE REVIEW

**Comment by sheymann** [comment]
Thanks @qinfchen ! I'll review your PR next week.

**Comment by sheymann** [comment]
Hello @qinfchen , what is the difference between `labelAlignment` and `defaultLabelAlignment`? Both settings have the same behavior.

**Comment by qinfchen** [comment]
There is no difference. `defaultLabelAlignment` is the default value for `labelAlignment`.  `defaultLabelAlignment`  is not needed. Good catch!

**Comment by sheymann** [comment]
Ok I've fixed it and manually merged into the branch https://github.com/Linkurious/linkurious.js/tree/feature/labelAlignment

The setting is called `labelAlignment`.

I've also modified the plugin sigma.renderers.linkurious to handle this setting. In this renderer, label hover background will also be displayed if `labelAlignment: 'center'` for readability purpose.

Thank you for your contribution!

**Comment by qinfchen** [comment]
Thanks @sheymann, sorry about the delay. I was swamped with other things and forgot about this PR...

**Comment by sheymann** [comment]
You're welcome, I wanted to do it pretty fast to use it.

**Pull request closed without merging**
