### PR TITLE
Plugin/tooltips Delay hide tooltip

### PR DESCRIPTION
**Pull request by alfredopacino**
Need a delay time from the hide tooltip event (outNode,outEdge) and the actual hide tooltip action, in order to make the buttons on tooltip actually clickable.

### CODE REVIEW

**Comment by sheymann** [comment]
Now the changes can be easily spotted, please edit the code of the plugin so that:

- if the listened event is 'outNode' or 'outEdge',
- and after a configurable? delay,
- call `cancel();` if the tooltip element has not the focus.

**Comment by alfredopacino** [comment]
outNode,outEdge are just examples. The plugin has an easy initialization:
```var config = {
      node: {
    show: 'overNode',
    hide: 'outNode',
```
This delay should be a general setting no matter what the hide event is. So I don't think the first of your 3 points should be done. About the other 2, i'm not into sigmajs core code enough to make this edit. For example, how do you think to get if the tooltip has the focus? Mine is a jquery way, obiouvsly it's not a valid solution in this case.

**Comment by alfredopacino** [comment]
i added just a timeout, the tooltip focus is still unhanded

**Comment by sheymann** [comment]
The timeout should be 0 in case of `clickStage` event otherwise it feels laggy.

**Comment by alfredopacino** [comment]
Yep, well anyway it's a secondary issue, the main problem here is track the tooltip focus..

**Comment by alfredopacino** [comment]
awesome! thanks

**Pull request closed without merging**
