### PR TITLE
Neo4j timeout

### PR DESCRIPTION
**Pull request by shlgug**

### CODE REVIEW

**Comment by sheymann** [comment]
Hi, thanks for the patch! Can you add what version of Neo4j you used for testing?

@ekkis is it working for you?

**Comment by shlgug** [comment]
Hi

Neo4j 2.2.2

Where should I add it?

Thanks

**Comment by sheymann** [comment]
In the param comment please. Timeouts are a useful addition of Neo4j 2.x but I don't remember which version starts to support them exactly.

**Comment by sheymann** [comment]
reviewed, thanks!

**Pull request merged**
