### PR TITLE
A* plugin, v1.0.1

### PR DESCRIPTION
**Pull request by A----**
Fixes A----/sigma-pathfinding-astar#1

Also, a running example can now be found here: http://a----.github.io/sigma-pathfinding-astar/

### CODE REVIEW

**Comment by sheymann** [comment]
Hi @A---- can you create PR to `develop` instead of `master` please? `develop` is the main branch, while `master` is the fork of sigma.js.

See https://github.com/Linkurious/linkurious.js/wiki/How-to-fix-bugs

**Comment by sheymann** [comment]
Manually merged into develop

**Comment by A----** [comment]
Sorry about that, didn't have the time to do this.

**Comment by A----** [comment]
Shouldn't you change the default branch to `develop` in the project settings?

**Comment by sheymann** [comment]
No worries, `develop` is already the default branch but github uses `master` by default when creating a PR unless you change it. I consider to rename `master` -> `stable` and `develop` -> `master`.

**Pull request closed without merging**
